config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
  post '/index', to: 'flats#index', as: :postindex
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
  validates :price_per_night, numericality: true
  validates :number_of_guests, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :destroy, :update, :edit]

  def index
    if !params[:search].nil?
      @search = params[:search]
      @flats = Flat.where("name LIKE '%#{@search}%'")
    else
      @flats = Flat.all
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @edition = false
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def show
    array = @flat.address.split(" ")
    texte = array.join("+")
    @url = "https://maps.googleapis.com/maps/api/staticmap?center=" + texte + "&zoom=13&size=600x300&maptype=roadmap&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318&markers=color:red%7Clabel:C%7C40.718217,-73.998284&key=AIzaSyAy57IuL7mJv6r2Ilz6nyDY3_7AQve3ZBU"

  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  def edit
    @edition = true
    render :new
  end

  def update
    @edition = false
    @flat.update(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def search_params
    params.require(:flat).permit(:search)
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_banner.html.erb
<div class="banner">
  <div class="image">
    <img src="https://source.unsplash.com/random/750x300">
  </div>
  <div class="image">
    <img src="https://source.unsplash.com/random/750x301">
  </div>
</div>

app/views/flats/index.html.erb
<%= render 'banner' %>

<div class="header">
  <form action='/index' method='post'>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type='text' name='search'>
    <input type='submit' value='Search'>
  </form>
  <%= link_to "Add flat", new_flat_path, class: "button" %>
</div>

<div class="flats">
  <% @flats.each do |f| %>
  <div class="flat">
    <div class="flattext">
      <h3><%= f.name %></h3>
      <h4><%= f.address %></h4>
    </div>
    <div class="flaticons">
      <i class="fas fa-euro-sign"></i><%= f.price_per_night %>
      <i class="fas fa-user-alt"></i><%= f.number_of_guests %>
    </div>
    <div class="flatlinks">
      <%= link_to "More info", flat_path(f) %>
      <%= link_to "Delete", flat_path(f), method: :delete, data: { confirm: "Are you sure?"} %>
    </div>
  </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<%= render 'banner' %>

<%= form_for(@flat) do |f| %>
  <% if @flat.errors.any? || @edition %>
    <% if !@edition %>
      <div class="errors-container">
        <ul>
          <% @flat.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.text_field :name, value: @flat.name %>
    <%= f.text_field :address, value: @flat.address %>
    <%= f.text_field :description, value: @flat.description %>
    <%= f.number_field :price_per_night, value: @flat.price_per_night %>
    <%= f.number_field :number_of_guests, value: @flat.number_of_guests %>
  <% else %>
    <%= f.text_field :name %>
    <%= f.text_field :address %>
    <%= f.text_field :description %>
    <%= f.number_field :price_per_night %>
    <%= f.number_field :number_of_guests %>
  <% end %>
  <% if @edition %>
    <%= f.submit "Edit flat", method: :patch, class: "btn btn-primary"%>
  <% else %>
    <%= f.submit "Add a flat", class: "btn btn-primary"%>
  <% end %>
<% end %>

app/views/flats/show.html.erb
<!-- <img src=<%= @url %> style="width:1000px;height:300px"> -->

<%= render 'banner' %>

<div>
<%= @flat.name %>
</div>
<div>
<%= @flat.address %>
</div>
<div>
<%= @flat.description %>
</div>
<div>
<%= @flat.price_per_night %>
<%= @flat.number_of_guests %>
</div>
<div>
<%= link_to "Edit flat", edit_flat_path(@flat) %>
<%= link_to "Back to home", flats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>